export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "OpenUserLab"
export const APP_DESCRIPTION = process.env.NEXT_PUBLIC_APP_DESCRIPTION || "Generated by create next app"
export const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'

export const LATEST_STUDIES_LIMIT = Number(process.env.LATEST_STUDIES_LIMIT) || 6;

export const signInDefaultValues = {
    email: 'alice@example.com',
    password: '123456'
}

export const signUpDefaultValues = {
    name: 'Hsiang',
    email: 'hsiang@example.com',
    password: '123456',
    confirmPassword: '123456',
    isResearcher: "true",
    institution: "University of Nottingham",
}
