export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "OpenUserLab"
export const APP_DESCRIPTION = process.env.NEXT_PUBLIC_APP_DESCRIPTION || "Generated by create next app"
export const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'